const logoImg = [
    
  { id: 1, src: './logos/consultation.png', alt: 'Малын эмч' },
  { id: 2, src: './logos/civil.png', alt: 'Барилгын инженер' },
  { id: 3, src: './logos/gear_15129555.png', alt: 'Гидромеханик инженер' },
  { id: 4, src: './logos/chemical.png', alt: 'Хүнс үйлдвэрлэлийн технологич инженер (Хятадтай хамтарсан 3+1)' },
  { id: 5, src: './logos/chemical.png', alt: 'Хүнс үйлдвэрлэлийн технологич инженер' },
  { id: 6, src: './logos/agricultur.png', alt: 'Хөдөө аж ахуйн инженер' },

  { id: 7, src: './logos/electrical-engineering.png', alt: 'Цахилгаан хангамжийн инженер' },
  { id: 8, src: './logos/mechanical-engineering.png', alt: 'Механик инженер' },
  { id: 9, src: 'src/logos/smart_city.png', alt: 'Ухаалаг технологийн инженер (хаа)' },
  

  { id: 10, src: 'images/smart_tech.png', alt: 'Ухаалаг технологийн инженер' },
  { id: 11, src: 'images/ecologist.png', alt: 'Экологич' },
  { id: 12, src: 'images/soil.png', alt: 'Хөрс судлал агрохимич' },
  { id: 13, src: 'images/landscape.png', alt: 'Ландшафтын архитекторч' },
  { id: 14, src: 'images/veg_agronomist.png', alt: 'Ногооны агрономч' },
  { id: 15, src: 'images/pasture_agronomist.png', alt: 'Бэлчээр тэжээлийн агрономч' },
  { id: 16, src: 'images/forestry.png', alt: 'Ойн аж ахуйн инженер' },
  { id: 17, src: 'images/env_rehab.png', alt: 'Байгаль орчны нөхөн сэргээлтийн мэргэжилтэн' },
  { id: 18, src: 'images/env_assess.png', alt: 'Хүрээлэн буй орчны хяналт үнэлгээний мэргэжилтэн' },
  { id: 19, src: 'images/cadastre.png', alt: 'Газрын кадастрын инженер' },
  { id: 20, src: 'images/land_planner.png', alt: 'Газар зохион байгуулагч, инженер' },
  { id: 21, src: 'images/agronomist.png', alt: 'Агрономч' },
  { id: 22, src: 'images/plant_protection.png', alt: 'Ургамал хамгаалал, хорио цээрийн мэргэжилтэн' },
  { id: 23, src: 'images/geodesy.png', alt: 'Геодезийн инженер' },
  { id: 24, src: 'images/medicinal_plants.png', alt: 'Уламжлалт анагаах ухааны эмийн ургамал зүйч' },
  { id: 25, src: 'images/fishery.png', alt: 'Загасны аж ахуй' },
  { id: 26, src: 'images/biotech.png', alt: 'Биотехнологич' },
  { id: 27, src: 'images/biotech2.png', alt: 'Биотехнологич' },
  { id: 28, src: 'images/commodity.png', alt: 'Таваар судлал, түүхий эдийн шинжээч' },
  { id: 29, src: 'images/meat_dairy.png', alt: 'Мах, сүү үйлдвэрлэлийн технологич' },
  { id: 30, src: 'images/food_safety.png', alt: 'Хүнсний чанар, эрүүл ахуйн үнэлгээ' },
  { id: 31, src: 'images/feed_tech.png', alt: 'Тэжээл, бэлчээрийн технологич' },
  { id: 32, src: 'images/livestock_manager.png', alt: 'Мал аж ахуйн үйлдвэрлэлийн менежер' },
  { id: 33, src: 'images/livestock_specialist.png', alt: 'Мал зүйч' },
  { id: 34, src: 'images/horse_sport.png', alt: 'Морин спортын менежер' },
  { id: 35, src: 'images/business_economist.png', alt: 'Бизнесийн эдийн засагч' },
  { id: 36, src: 'images/economic_model.png', alt: 'Эдийн засгийн математик загварчлал' },
  { id: 37, src: 'images/marketing.png', alt: 'Маркетингийн менежмент' },
  { id: 38, src: 'images/tourism_marketing.png', alt: 'Аялал жуулчлалын маркетингийн менежер' },
  { id: 39, src: 'images/ecommerce_marketing.png', alt: 'Цахим худалдааны маркетингийн менежер' },
  { id: 40, src: 'images/economist_statistician.png', alt: 'Эдийн засагч, статистикч' },
  { id: 41, src: 'images/banking.png', alt: 'Банк, санхүүгийн менежер' },
  { id: 42, src: 'images/accounting.png', alt: 'Нягтлан бодогч' },
  { id: 43, src: 'images/business_admin.png', alt: 'Бизнесийн удирдлага' },
  { id: 44, src: 'images/business_analyst.png', alt: 'Бизнесийн шинжээч' },
  { id: 45, src: 'images/production_manager.png', alt: 'Үйлдвэрлэлийн менежер' },
  { id: 46, src: 'images/hr_manager.png', alt: 'Хүний нөөцийн менежер' },
  { id: 47, src: 'images/agri_cyber.png', alt: 'Хөдөө аж ахуйн кибернетик' },
  { id: 48, src: 'images/tourism_marketing2.png', alt: 'Аялал жуулчлалын маркетингийн менежер' },
  { id: 49, src: 'images/biology_hunting.png', alt: 'Биологи-агнуур зүйч' },
  { id: 50, src: 'images/agri_chem_tech.png', alt: 'Хөдөө аж ахуйн бүтээгдэхүүний хими технологич' },
  { id: 51, src: 'images/it_engineer.png', alt: 'Мэдээллийн системийн инженер' },
  { id: 52, src: 'images/software_engineer.png', alt: 'Программ хангамжийн инженер' },
  { id: 53, src: 'images/nature_tourism.png', alt: 'Байгалийн аялал жуулчлалын менежер' }
];
export default logoImg;